version: '2.1'

services:
  web:
    image: kontena-whoami-develop
    build:
      dockerfile: ${DOCKERFILE:-Dockerfile}
      context: .
    command: ./start
    ports:
      - "80:80"
    environment:
      - RACK_ENV=${RACK_ENV:-production}
    volumes:
      - .:/app
      - /usr/local/bundle
