version: '2'

services:
  web:
    image: ${IMAGE_NAME:-lellik}
    build:
      context: .
    command: ./start
    deploy:
      strategy: daemon
      wait_for_port: 80
    stateful: true
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=80
      - KONTENA_LB_VIRTUAL_HOSTS=${LOADBALANCER_VHOSTS}
      - RACK_ENV=production
    external_links:
      - ${LOADBALANCER_SERVICE_NAME}
    health_check:
      protocol: http
      port: 80
      interval: 30
      uri: /__health_check
      initial_delay: 60
      timeout: 2
