#!/usr/bin/env sh
set -e

if [ "$RACK_ENV" == "development" ]; then
  bundle --with "development test"
else
  bundle --without "development test"
fi

_term() {
  echo "Caught SIGTERM signal!"
  kill -TERM "$child" 2>/dev/null
}

trap _term SIGTERM

bundle exec rackup -s Puma -o 0.0.0.0 -p 80 &
child=$!
wait "$child"
